[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.2", features = ["chrono"] }
diesel-async = { version = "0.5", features = ["postgres"] }
chrono = "0.4"
rocket = { version = "0.5", features = ["json"] }
