services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app_db
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]

  redis:
    image: redis:latest

  app:
    build: .
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres/app_db
      - |
        ROCKET_DATABASES={
          postgres={url=postgres://postgres:postgres@postgres/app_db},
          redis={url=redis://redis:6379}
        }
      - SMTP_HOST=smtp.gmail.com
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
      - ./fish_history:/root/.local/share/fish
      - ./fish_config:/root/.config/fish
